Setting to never make notifications ongoing
Exception: alarm notification, as it requires user interaction

Change-Id: I382fe7ec6243474841abd18010782a720dc8dccc